#!/bin/bash
#m10k_build_plugin test file

# Unpack source
hg clone https://hg.mozilla.org/mozilla-central

# Goes into project directorry
cd mozilla*

# Read configuration to be tested
read PERMUTATION

# Set FLAGS to the options from permutation
export CFLAGS="$PERMUTATION"

./mach mercurial-setup || exit $?

./mach build


